<a href="https://colab.research.google.com/github/yagyanshsharma/Career-data-analysis/blob/main/Career_DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Employee Career Survey Analysis**![linear-flat-visitor-analytics-website-hero-image-illustration-seo-smm-online-marketing-concept-laptop-tablet-with-report-data-screen_126523-2649.avif]()

In [31]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "png"

In [17]:
Data = pd.read_csv("Career Survey Data Analysis.csv")

In [18]:
Data

,Your Current Country.,Your Current Zip Code / Pin Code,Your Gender,Which of the below factors influence the most about your career aspirations ?,Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.,How likely is that you will work for one employer for 3 years or more ?,Would you work for a company whose mission is not clearly defined and publicly posted.,How likely would you work for a company whose mission is misaligned with their public actions or even their product ?,How likely would you work for a company whose mission is not bringing social impact ?,What is the most preferred working environment for you.,Which of the below Employers would you work with.,Which type of learning environment that you are most likely to work in ?,Which of the below careers looks close to your Aspirational job ?,What type of Manager would you work without looking into your watch ?,Which of the following setup you would like to work ?
0,India,273005,Male,People who have changed the world for better,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",No,Will NOT work for them,4,Fully Remote with No option to visit offices,Employer who rewards learning and enables that...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...","Work alone, Work with 2 to 3 people in my team..."
1,India,851129,Male,People who have changed the world for better,"No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,1,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
2,India,123106,Female,Social Media like LinkedIn,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,7,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Trial and error b...",Manage and drive End-to-End Projects or Produc...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
3,India,834003,Male,"People from my circle, but not family members","No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,6,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Manag...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
4,India,301019,Female,Influencers who had successful careers,"No, But if someone could bare the cost I will",Will work for 3 years or more,No,Will NOT work for them,5,Fully Remote with Options to travel as and whe...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,India,605008,Male,"People from my circle, but not family members","Yes, I will earn and do that",Will work for 3 years or more,No,Will NOT work for them,7,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Learning by obser...","Design and Creative strategy in any company, B...",Manager who sets goal and helps me achieve it,Work with more than 10 people in my team
231,India,722207,Male,"People from my circle, but not family members",No I would not be pursuing Higher Education ou...,"This will be hard to do, but if it is the righ...",Yes,Will work for them,5,Hybrid Working Environment with less than 3 da...,Employer who rewards learning and enables that...,"Learning by observing others, Trial and error ...","Business Operations in any organization, Look ...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
232,India,604102,Female,People who have changed the world for better,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,4,Hybrid Working Environment with less than 10 d...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...","Design and Creative strategy in any company, B...",Manager who sets goal and helps me achieve it,Work with more than 10 people in my team
233,India,122002,Male,People who have changed the world for better,"Yes, I will earn and do that","No way, 3 years with one employer is crazy",No,Will NOT work for them,7,Hybrid Working Environment with less than 15 d...,Employer who rewards learning and enables that...,"Self Paced Learning Portals, Instructor or Exp...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
234,India,605102,Female,My Parents,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",Yes,Will work for them,5,Every Day Office Environment,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Desig...",Manager who sets targets and expects me to ach...,Work with 7 to 10 or more people in my team

In [19]:
#first of all we will inspect the columns of the dataset
Data.columns

Index(['Your Current Country.', 'Your Current Zip Code / Pin Code',
       'Your Gender',
       'Which of the below factors influence the most about your career aspirations ?',
       'Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.',
       'How likely is that you will work for one employer for 3 years or more ?',
       'Would you work for a company whose mission is not clearly defined and publicly posted.',
       'How likely would you work for a company whose mission is misaligned with their public actions or even their product ?',
       'How likely would you work for a company whose mission is not bringing social impact ?',
       'What is the most preferred working environment for you.',
       'Which of the below Employers would you work with.',
       'Which type of learning environment that you are most likely to work in ?',
       'Which of the below careers looks close to your Aspirational job ?',
       'What type of Manager would you work without looking into your watch ?',
       'Which of the following setup you would like to work ?'],
      dtype='object')

In [20]:
Country = Data["Your Current Country."].value_counts()
label = Country.index
counts = Country.values
colors = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue']
fig = go.Figure(data=[go.Pie(labels = label, values = counts)])
fig.update_layout(title_text = 'Country')
fig.update_traces(hoverinfo = 'label+value', textinfo = 'percent', textfont_size = 30,
                  marker = dict(colors = colors, line = dict(color = 'black', width = 2)))
fig.show()

In [21]:
Country

Your Current Country.
India                       231
Germany                       2
United Arab Emirates          1
United States of America      1
Name: count, dtype: int64

# **Factors that influencing Career Aspirations**

In [22]:
Data.head()

,Your Current Country.,Your Current Zip Code / Pin Code,Your Gender,Which of the below factors influence the most about your career aspirations ?,Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.,How likely is that you will work for one employer for 3 years or more ?,Would you work for a company whose mission is not clearly defined and publicly posted.,How likely would you work for a company whose mission is misaligned with their public actions or even their product ?,How likely would you work for a company whose mission is not bringing social impact ?,What is the most preferred working environment for you.,Which of the below Employers would you work with.,Which type of learning environment that you are most likely to work in ?,Which of the below careers looks close to your Aspirational job ?,What type of Manager would you work without looking into your watch ?,Which of the following setup you would like to work ?
0,India,273005,Male,People who have changed the world for better,"Yes, I will earn and do that","This will be hard to do, but if it is the righ...",No,Will NOT work for them,4,Fully Remote with No option to visit offices,Employer who rewards learning and enables that...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...","Work alone, Work with 2 to 3 people in my team..."
1,India,851129,Male,People who have changed the world for better,"No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,1,Fully Remote with Options to travel as and whe...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Instructor or Exp...","Business Operations in any organization, Build...","Manager who explains what is expected, sets a ...",Work with 5 to 6 people in my team
2,India,123106,Female,Social Media like LinkedIn,"Yes, I will earn and do that",Will work for 3 years or more,Yes,Will work for them,7,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Self Paced Learning Portals, Trial and error b...",Manage and drive End-to-End Projects or Produc...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."
3,India,834003,Male,"People from my circle, but not family members","No, But if someone could bare the cost I will","This will be hard to do, but if it is the righ...",No,Will NOT work for them,6,Hybrid Working Environment with less than 15 d...,Employer who pushes your limits by enabling an...,"Instructor or Expert Learning Programs, Trial ...","Business Operations in any organization, Manag...","Manager who explains what is expected, sets a ...",Work with 2 to 3 people in my team
4,India,301019,Female,Influencers who had successful careers,"No, But if someone could bare the cost I will",Will work for 3 years or more,No,Will NOT work for them,5,Fully Remote with Options to travel as and whe...,Employer who appreciates learning and enables ...,"Self Paced Learning Portals, Learning by obser...",Teaching in any of the institutes/online or Of...,"Manager who explains what is expected, sets a ...","Work with 2 to 3 people in my team, Work with ..."

In [23]:
Question1 = Data["Which of the below factors influence the most about your career aspirations ?"].value_counts()
label = Question1.index
counts = Question1.values
# Expand colors to accommodate more categories
colors = px.colors.qualitative.Plotly # Using a Plotly qualitative color sequence for more colors
fig = go.Figure(data = [go.Pie(labels = label, values = counts, marker=dict(colors=colors))])
fig.update_layout(title_text = ("Factors Influencing Career Aspirations"))
fig.update_traces(hoverinfo = "label+value", textinfo = "percent", textfont_size = 12,
                  marker = dict(line = dict(color = "black", width = 2)))
fig.show()

In [24]:
#Now we will analyse and visualise who wants to go abroad for higher education or post graduation,
#and what reasons they'll go or will not go.
Q2 = "Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it."
Q2 = Data[Q2].value_counts()

In [25]:
Q2

Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.
Yes, I will earn and do that                                    110
No I would not be pursuing Higher Education outside of India     65
No, But if someone could bare the cost I will                    60
Name: count, dtype: int64

In [26]:
label = Q2.index
counts = Q2.values
colors = ['lightgreen','skyblue']
fig = go.Figure(data =[go.Pie(labels = label, values= counts , marker = dict(colors = colors))])
fig.update_layout(title_text = "Would you definitely pursue a Higher Education / Post Graduation outside of India ? If only you have to self sponsor it.")
fig.update_traces(hoverinfo = "label+value", textinfo = "percent", textfont_size= 12,
                     marker = dict(line =dict(color = 'black', width = 3)))

In [27]:
#now we will analyse and visualise how many people wantb to work on company for 3 years, more than 3 years,
#or less than 3 years
Q3 = "How likely is that you will work for one employer for 3 years or more ?"
Q3 = Data[Q3].value_counts()
Q3

How likely is that you will work for one employer for 3 years or more ?
This will be hard to do, but if it is the right company I would try    139
Will work for 3 years or more                                           79
No way, 3 years with one employer is crazy                              17
Name: count, dtype: int64

In [28]:
label = Q3.index
counts = Q3.values
colors = ['aqua', 'green']
fig = go.Figure(data =[go.Pie(labels = label, values= counts, marker = dict(colors = colors))])
fig.update_layout(title_text = "How likely is that you will work for one employer for 3 years or more ?")
fig.update_traces(hoverinfo = "label+value", textinfo = "percent", textfont_size = 13,
                  marker = dict(line = dict(color = "black", width = 3)))
fig.show()

In [29]:
#now we will analyse and visualise which working enviroment genz prefers to work in
#column 10
Q4 = Data["What is the most preferred working environment for you."].value_counts()
label = Q4.index
counts = Q4.values
colors = ['green','blue','yellow']
fig = go.Figure(data = [go.Pie(labels = label, values=counts, marker = dict(colors = colors))])
fig.update_layout(title_text = "What is the most preferred working environment for you.")
fig.update_traces(hoverinfo ='label+value', textinfo = 'percent', textfont_size= 13,
                  marker = (dict (line = dict(color = 'black', width = 3))))
fig.show()

In [30]:
Q5 = Data['Which of the below careers looks close to your Aspirational job ?'].value_counts()
labels = Q5.index
counts = Q5.values
colors = ['orange', 'gray','lightblue']
fig = go.Figure(data =[go.Pie(labels = label, values = counts, marker = dict(colors = colors))])
fig.update_layout(title_text = "Which of the below careers looks close to your Aspirational job ?")
fig.update_traces(hoverinfo ="label+value", textinfo = 'percent', textfont_size = 13,
                  marker = dict(line = dict(color = 'black', width = 3)))
fig.show()

# **Conclusion**

In this project i analyzed and visualized data from an employers career survey.I explored which countries most of the respondents come from whether they are interested in studying or working abroad and whether they are likely to stay in a company for at least 3 years. I also looked at the key factors that influence genzs career choices their preferred job roles and how closely different career options match their aspirational jobs.

# **Key Insights**

**-** We observed that around 98% of the survey participants are from india.

**-** Data shows that approximately 33% of genz's career aspirations are shaped by parental influence.

**-** We also observed that around 46-47% of people want to pursue higher education  or post-graduation abroad and earn there.

**-** while 59% of genz's find 3-year tenure difficult, they would stay longer for the righ company.

**-** Genz,s preference is highest at 26% for remote work' and lowest at 4% for fully remote with zero office access.

**-** Genz prefference peaks at 21% for remote work with travel options, while its lowest at 14% of hybrid setups requiring less than 10 days or a 3 days a month in the office.

**Thank you!**

This project was done as part of my data analysis practice.